// Wait for the DOM to be fully loaded before running the script
document.addEventListener('DOMContentLoaded', () => {

    // =================================================================
        // 1. Responsive Hamburger Menu
            // This feature toggles the visibility of the navigation links on smaller screens.
                // =================================================================
                    const hamburgerMenu = document.querySelector('.hamburger-menu');
                        const navLinks = document.querySelector('.nav-links');

                            hamburgerMenu.addEventListener('click', () => {
                                    // Toggle the 'active' class on the navigation links to show/hide them
                                            navLinks.classList.toggle('active');
                                                });

                                                    // =================================================================
                                                        // 2. Contact Form Validation
                                                            // This feature prevents the form from submitting if fields are empty or invalid.
                                                                // It's a custom validation, as required by the assignment.
                                                                    // =================================================================
                                                                        const contactForm = document.getElementById('contact-form');

                                                                            // Check if the contact form exists on the current page before adding a listener
                                                                                if (contactForm) {
                                                                                        contactForm.addEventListener('submit', (event) => {
                                                                                                    // Prevent the default form submission
                                                                                                                event.preventDefault();

                                                                                                                            // Get form elements
                                                                                                                                        const nameInput = document.getElementById('name');
                                                                                                                                                    const emailInput = document.getElementById('email');
                                                                                                                                                                const messageInput = document.getElementById('message');
                                                                                                                                                                            
                                                                                                                                                                                        // Get error message spans
                                                                                                                                                                                                    const nameError = document.getElementById('name-error');
                                                                                                                                                                                                                const emailError = document.getElementById('email-error');
                                                                                                                                                                                                                            const messageError = document.getElementById('message-error');

                                                                                                                                                                                                                                        let isValid = true;

                                                                                                                                                                                                                                                    // Clear previous error messages
                                                                                                                                                                                                                                                                nameError.style.display = 'none';
                                                                                                                                                                                                                                                                            emailError.style.display = 'none';
                                                                                                                                                                                                                                                                                        messageError.style.display = 'none';

                                                                                                                                                                                                                                                                                                    // Validate Name field
                                                                                                                                                                                                                                                                                                                if (nameInput.value.trim() === '') {
                                                                                                                                                                                                                                                                                                                                nameError.textContent = 'Name is required.';
                                                                                                                                                                                                                                                                                                                                                nameError.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                isValid = false;
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                        // Validate Email field
                                                                                                                                                                                                                                                                                                                                                                                                    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                                                                                                                                                                                                                                                                                                                                                                                                                if (emailInput.value.trim() === '') {
                                                                                                                                                                                                                                                                                                                                                                                                                                emailError.textContent = 'Email is required.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                emailError.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                isValid = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (!emailRegex.test(emailInput.value)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            emailError.textContent = 'Please enter a valid email address.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            emailError.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isValid = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Validate Message field
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (messageInput.value.trim() === '') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                messageError.textContent = 'Message is required.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                messageError.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                isValid = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // If all fields are valid, you can proceed with form submission logic
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (isValid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // In a real application, you would send the data to a server here.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // For this assignment, we'll just show an alert.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert('Thank you for your message! We will get back to you soon.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    contactForm.reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            